[phases.setup]
nixPkgs = ['python311', 'nodejs_20']

[phases.install]
cmds = [
  'python3 -m pip install -r backend/requirements.txt',
  'npm --prefix frontend ci',
  'npm --prefix frontend run build'
]

[start]
cmd = 'cd backend && python main.py'
